name: Android CI (Debug APK)
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK packages
        run: |
          sdkmanager --install "platform-tools" "platforms;android-35" "build-tools;35.0.0"
          yes | sdkmanager --licenses

      - name: Unzip project
        run: |
          unzip -o UltraMaxLite-Android-WGReady.zip

      - name: Build Debug APK (Gradle 8.5)
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.5
          build-root-directory: UltraMaxLite-Android-Starter
          arguments: assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: UltraMaxLite-debug
          path: UltraMaxLite-Android-Starter/app/build/outputs/apk/debug/*.apk
